from django.conf.urls import include, url
from django.contrib import admin

from rest_framework import routers
from positions.views import PositionsViewSet
# this is DRF router for REST API viewsets
router = routers.DefaultRouter()

# register REST API endpoints with DRF router
router.register(r'positions', PositionsViewSet, r"positions")

urlpatterns = [
    # default django admin interface
    url(r'^admin/', include(admin.site.urls)),

    # REST API root view (generated by DRF router)
    url(r'^api/', include(router.urls, namespace='api')),
]
